#!/bin/bash

make 
make testando
for TEXTO in Mussum Cinnamon 
do
    for FUNCAO in Devolve Rank Remove Select
    do
        echo texto: $TEXTO função: $FUNCAO
        echo digite enter para continuar
        read
        for ED in AB A23 TR RN VO VD LO LD HS
        do
            ./unit_test ${TEXTO}.txt ${ED} < entradas/entrada${FUNCAO}${TEXTO}.txt > saidas/Saida${ED}${FUNCAO}${TEXTO}.txt
            ./contador < saidas/Saida${ED}${FUNCAO}${TEXTO}.txt > testesDeTempo/${ED}${FUNCAO}${TEXTO}.txt
            if [ $ED != "AB" ]
            then
                echo comparando $ED com $ANTERIOR
                echo saidas/Saida${ED}${FUNCAO}${TEXTO}.txt saidas/Saida${ANTERIOR}${FUNCAO}${TEXTO}.txt| ./testando
            fi
            ANTERIOR=$ED
        done
    done
done