#!/bin/bash

make
make testando
./unit_test mussum.txt AB < entradaSelectMussum.txt > AB.txt
./unit_test mussum.txt RN < entradaSelectMussum.txt > RN.txt
./unit_test mussum.txt VO < entradaSelectMussum.txt > VO.txt
./unit_test mussum.txt TR < entradaSelectMussum.txt > TR.txt
./unit_test mussum.txt LO < entradaSelectMussum.txt > LO.txt
./unit_test mussum.txt LD < entradaSelectMussum.txt > LD.txt
./unit_test mussum.txt VD < entradaSelectMussum.txt > VD.txt
./unit_test mussum.txt HS < entradaSelectMussum.txt > HS.txt
./unit_test mussum.txt A23 < entradaSelectMussum.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
