#!/bin/bash

make
make testando

valgrind --leak-check=full ./unit_test thecinnamoncub.txt AB < entradaDeleteCinnamon.txt > AB.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt RN < entradaDeleteCinnamon.txt > RN.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt VO < entradaDeleteCinnamon.txt > VO.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt TR < entradaDeleteCinnamon.txt > TR.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt LO < entradaDeleteCinnamon.txt > LO.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt LD < entradaDeleteCinnamon.txt > LD.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt VD < entradaDeleteCinnamon.txt > VD.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt HS < entradaDeleteCinnamon.txt > HS.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt A23 < entradaDeleteCinnamon.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
