#!/bin/bash

make
make testando

valgrind --leak-check=full ./unit_test mussum.txt AB < entradaRemoveMussum.txt > AB.txt
valgrind --leak-check=full ./unit_test mussum.txt RN < entradaRemoveMussum.txt > RN.txt
valgrind --leak-check=full ./unit_test mussum.txt VO < entradaRemoveMussum.txt > VO.txt
valgrind --leak-check=full ./unit_test mussum.txt TR < entradaRemoveMussum.txt > TR.txt
valgrind --leak-check=full ./unit_test mussum.txt LO < entradaRemoveMussum.txt > LO.txt
valgrind --leak-check=full ./unit_test mussum.txt LD < entradaRemoveMussum.txt > LD.txt
valgrind --leak-check=full ./unit_test mussum.txt VD < entradaRemoveMussum.txt > VD.txt
valgrind --leak-check=full ./unit_test mussum.txt HS < entradaRemoveMussum.txt > HS.txt
valgrind --leak-check=full ./unit_test mussum.txt A23 < entradaRemoveMussum.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
