#!/bin/bash

make
make testando

valgrind --leak-check=full ./unit_test thecinnamoncub.txt AB < entradaRemoveCinnamon.txt > AB.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt RN < entradaRemoveCinnamon.txt > RN.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt VO < entradaRemoveCinnamon.txt > VO.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt TR < entradaRemoveCinnamon.txt > TR.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt LO < entradaRemoveCinnamon.txt > LO.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt LD < entradaRemoveCinnamon.txt > LD.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt VD < entradaRemoveCinnamon.txt > VD.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt HS < entradaRemoveCinnamon.txt > HS.txt
valgrind --leak-check=full ./unit_test thecinnamoncub.txt A23 < entradaRemoveCinnamon.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
