#!/bin/bash

make
make testando
./unit_test thecinnamoncub.txt AB < entradaCinnamon.txt > AB.txt
./unit_test thecinnamoncub.txt RN < entradaCinnamon.txt > RN.txt
./unit_test thecinnamoncub.txt VO < entradaCinnamon.txt > VO.txt
./unit_test thecinnamoncub.txt TR < entradaCinnamon.txt > TR.txt
./unit_test thecinnamoncub.txt LO < entradaCinnamon.txt > LO.txt
./unit_test thecinnamoncub.txt LD < entradaCinnamon.txt > LD.txt
./unit_test thecinnamoncub.txt VD < entradaCinnamon.txt > VD.txt
./unit_test thecinnamoncub.txt HS < entradaCinnamon.txt > HS.txt
./unit_test thecinnamoncub.txt A23 < entradaCinnamon.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
