#!/bin/bash

make
make testando
./unit_test thecinnamoncub.txt AB < entradaSelectCinnamon.txt > AB.txt
./unit_test thecinnamoncub.txt RN < entradaSelectCinnamon.txt > RN.txt
./unit_test thecinnamoncub.txt VO < entradaSelectCinnamon.txt > VO.txt
./unit_test thecinnamoncub.txt TR < entradaSelectCinnamon.txt > TR.txt
./unit_test thecinnamoncub.txt LO < entradaSelectCinnamon.txt > LO.txt
./unit_test thecinnamoncub.txt LD < entradaSelectCinnamon.txt > LD.txt
./unit_test thecinnamoncub.txt VD < entradaSelectCinnamon.txt > VD.txt
./unit_test thecinnamoncub.txt HS < entradaSelectCinnamon.txt > HS.txt
./unit_test thecinnamoncub.txt A23 < entradaSelectCinnamon.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
