#!/bin/bash

make
make testando
./unit_test thecinnamoncub.txt AB < entradaDevolveCinnamon.txt > AB.txt
./unit_test thecinnamoncub.txt RN < entradaDevolveCinnamon.txt > RN.txt
./unit_test thecinnamoncub.txt VO < entradaDevolveCinnamon.txt > VO.txt
./unit_test thecinnamoncub.txt TR < entradaDevolveCinnamon.txt > TR.txt
./unit_test thecinnamoncub.txt LO < entradaDevolveCinnamon.txt > LO.txt
./unit_test thecinnamoncub.txt LD < entradaDevolveCinnamon.txt > LD.txt
./unit_test thecinnamoncub.txt VD < entradaDevolveCinnamon.txt > VD.txt
./unit_test thecinnamoncub.txt HS < entradaDevolveCinnamon.txt > HS.txt
./unit_test thecinnamoncub.txt A23 < entradaDevolveCinnamon.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
