#!/bin/bash

make
make testando
./unit_test mussum.txt AB < entradaDevolveMussum.txt > AB.txt
./unit_test mussum.txt RN < entradaDevolveMussum.txt > RN.txt
./unit_test mussum.txt VO < entradaDevolveMussum.txt > VO.txt
./unit_test mussum.txt TR < entradaDevolveMussum.txt > TR.txt
./unit_test mussum.txt LO < entradaDevolveMussum.txt > LO.txt
./unit_test mussum.txt LD < entradaDevolveMussum.txt > LD.txt
./unit_test mussum.txt VD < entradaDevolveMussum.txt > VD.txt
./unit_test mussum.txt HS < entradaDevolveMussum.txt > HS.txt
./unit_test mussum.txt A23 < entradaDevolveMussum.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
