#!/bin/bash

make
make testando
./unit_test thecinnamoncub.txt AB < entradaRankCinnamon.txt > AB.txt
./unit_test thecinnamoncub.txt RN < entradaRankCinnamon.txt > RN.txt
./unit_test thecinnamoncub.txt VO < entradaRankCinnamon.txt > VO.txt
./unit_test thecinnamoncub.txt TR < entradaRankCinnamon.txt > TR.txt
./unit_test thecinnamoncub.txt LO < entradaRankCinnamon.txt > LO.txt
./unit_test thecinnamoncub.txt LD < entradaRankCinnamon.txt > LD.txt
./unit_test thecinnamoncub.txt VD < entradaRankCinnamon.txt > VD.txt
./unit_test thecinnamoncub.txt HS < entradaRankCinnamon.txt > HS.txt
./unit_test thecinnamoncub.txt A23 < entradaRankCinnamon.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
