#!/bin/bash

make
make testando
./unit_test mussum.txt AB < entradaRankMussum.txt > AB.txt
./unit_test mussum.txt RN < entradaRankMussum.txt > RN.txt
./unit_test mussum.txt VO < entradaRankMussum.txt > VO.txt
./unit_test mussum.txt TR < entradaRankMussum.txt > TR.txt
./unit_test mussum.txt LO < entradaRankMussum.txt > LO.txt
./unit_test mussum.txt LD < entradaRankMussum.txt > LD.txt
./unit_test mussum.txt VD < entradaRankMussum.txt > VD.txt
./unit_test mussum.txt HS < entradaRankMussum.txt > HS.txt
./unit_test mussum.txt A23 < entradaRankMussum.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt
