#!/bin/bash

make
make testando

for ED in AB A23 TR RN VO VD LO LD HS
do
    for TEXTO in Mussum Cinnamon
    do 
        echo " " | valgrind --leak-check=full ./unit_test ${TEXTO}.txt $ED
        echo Teste da estrutura de dado $ED com o texto $TEXTO concluído.
        echo pressione enter para continuar.
        read
    done
done
