#!/bin/bash

make
make testando

valgrind --leak-check=full ./unit_test cassilds.txt AB < entradaRemove.txt > AB.txt
valgrind --leak-check=full ./unit_test cassilds.txt RN < entradaRemove.txt > RN.txt
valgrind --leak-check=full ./unit_test cassilds.txt VO < entradaRemove.txt > VO.txt
valgrind --leak-check=full ./unit_test cassilds.txt TR < entradaRemove.txt > TR.txt
valgrind --leak-check=full ./unit_test cassilds.txt LO < entradaRemove.txt > LO.txt
valgrind --leak-check=full ./unit_test cassilds.txt LD < entradaRemove.txt > LD.txt
valgrind --leak-check=full ./unit_test cassilds.txt VD < entradaRemove.txt > VD.txt
valgrind --leak-check=full ./unit_test cassilds.txt HS < entradaRemove.txt > HS.txt
valgrind --leak-check=full ./unit_test cassilds.txt A23 < entradaRemove.txt > A23.txt


./testando < teste1.txt
./testando < teste2.txt
./testando < teste3.txt
./testando < teste4.txt
./testando < teste5.txt
./testando < teste6.txt
./testando < teste7.txt
./testando < teste8.txt